# Neurosint é um projeto sem fins lucrativos, feito por um familiar cuidador.
# Para habilitar o botão "Sponsor" do GitHub, descomente e preencha o seu handle/links.
# Doc: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [michelzf]
# custom: ["https://..."]
